<h2><?= $flash['success'][0] ?></h2>

<form action="/users" method="get">
    <input type="search" name="term" value="<?= htmlspecialchars($term) ?>" />
    <input type="submit" value="Search" />
</form>

<ul>
<?php foreach ($users as $user) : ?>
    <li><a href="/users/<?= $user['id'] ?>"><?php echo $user['name'] ?></li>
<?php endforeach ?>
</ul>

<a href="/users/new">New user</a>
<div></div>
<a href="/users/login">Login</a>