<form action="/users" method="post">
    <div>
        <label>
            Name
        <input type="text" name="user[name]" value="<?= htmlspecialchars($user['name']) ?>" />
        </label>
        <?php if (isset($errors['name'])) : ?>
            <div><?= $errors['name'] ?></div>
            <?php endif ?>
        </div>
        <div>
        <label>
            Email
        <input type="text" name="user[email]" value="<?= htmlspecialchars($user['email']) ?>" />
        </label>
        <?php if (isset($errors['email'])) : ?>
            <div><?= $errors['email'] ?></div>
            <?php endif ?>
        </div>
        <div>
        <label>
            Password
        <input type="text" name="user[password]" value="<?= htmlspecialchars($user['password']) ?>" />
        </label>
        <?php if (isset($errors['password'])) : ?>
            <div><?= $errors['password'] ?></div>
            <?php endif ?>
        </div>
        <div>
        <label>
            <select name="user[city]">
                <option <?= $user['city'] === 'Moscow' ? 'selected' : '' ?> value="Moscow">Moscow</option>
                <option <?= $user['city'] === 'NY' ? 'selected' : '' ?> value="NY">New York</option>
                <option <?= $user['city'] === 'Shanhai' ? 'selected' : '' ?> value="Shanhai">Shanhai</option>
            </select>
        </label>
        <?php if (isset($errors['city'])) : ?>
            <div><?= $errors['city'] ?></div>
            <?php endif ?>
        </div>
        <input type="submit" value="Sign up">
</form>